application: umichcrime
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /rest/.*
  script: rest.app

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
